// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXqDTZjBoGH7SmAfa9lOlxMulyb4ygBQ',
    appId: '1:739824187551:web:2c2e938415113261140aaa',
    messagingSenderId: '739824187551',
    projectId: 'jk-project-635f0',
    authDomain: 'jk-project-635f0.firebaseapp.com',
    storageBucket: 'jk-project-635f0.firebasestorage.app',
    measurementId: 'G-7800KFT3QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVJEd36PCXklIT9-WnXddiFuoWc0GwYfg',
    appId: '1:739824187551:android:852c6be96f9a140c140aaa',
    messagingSenderId: '739824187551',
    projectId: 'jk-project-635f0',
    storageBucket: 'jk-project-635f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB7Sfqo44VClK4YtFJWuxCX8kelVxYbEM',
    appId: '1:739824187551:ios:d8ab3dbfc74dbca0140aaa',
    messagingSenderId: '739824187551',
    projectId: 'jk-project-635f0',
    storageBucket: 'jk-project-635f0.firebasestorage.app',
    iosBundleId: 'com.example.jkEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB7Sfqo44VClK4YtFJWuxCX8kelVxYbEM',
    appId: '1:739824187551:ios:d8ab3dbfc74dbca0140aaa',
    messagingSenderId: '739824187551',
    projectId: 'jk-project-635f0',
    storageBucket: 'jk-project-635f0.firebasestorage.app',
    iosBundleId: 'com.example.jkEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVXqDTZjBoGH7SmAfa9lOlxMulyb4ygBQ',
    appId: '1:739824187551:web:718f4be097f10562140aaa',
    messagingSenderId: '739824187551',
    projectId: 'jk-project-635f0',
    authDomain: 'jk-project-635f0.firebaseapp.com',
    storageBucket: 'jk-project-635f0.firebasestorage.app',
    measurementId: 'G-MXDXFM9Y8J',
  );
}
